### ISSUE TITLE
Add an array

### ISSUE THREAD

**Issue by calra123** [calra123/Kotlin-codes#2]
Create a function that takes array as a parameter and finds the the sum of first n Prime numbers and returns the sum, n given by user.

**Comment by natehole** [comment]
Please assign to me

I can work on this in around 12 hours. I haven't worked with Kotlin but I am excited to try it out. For this function would you like it added in a new file or should this function go in index.kt?

**Comment by calra123** [comment]
Create a new file for the function

**Comment by nagavenkatakiran** [comment]
Hi Calra,
I would love to contribute
